# Generated by Django 3.1.1 on 2020-09-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='deficiencies',
        ),
    ]
