# Generated by Django 3.1.1 on 2020-09-06 19:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
