# Generated by Django 3.1.1 on 2020-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_userprofile_deficiencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disability_details',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disability_type',
            field=models.CharField(choices=[('N/A', 'None'), ('VIS', 'Visual'), ('AUD', 'Auditory'), ('PSY', 'Psychological'), ('PHY', 'Physical')], default='N/A', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_middle_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='father_status',
            field=models.CharField(choices=[('', ''), ('A', 'Alive'), ('D', 'Deceased'), ('U', 'Unknown')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_maiden_last_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_maiden_middle_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mother_status',
            field=models.CharField(choices=[('', ''), ('A', 'Alive'), ('D', 'Deceased'), ('U', 'Unknown')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preenlistment_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('REG', 'Regular'), ('FST', 'Freshman'), ('GRD', 'Graduating'), ('CCO', 'Cadet Officer')], default='REG', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('REG', 'Regular'), ('FST', 'Freshman'), ('GRD', 'Graduating'), ('CCO', 'Cadet Officer')], default='REG', max_length=3),
        ),
    ]
