# Generated by Django 3.1.1 on 2020-09-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200907_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
