# Generated by Django 3.1.1 on 2020-09-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200908_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
