# Generated by Django 3.1.1 on 2020-09-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200908_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('registration_status', models.BooleanField(default=False)),
                ('preenlistment_priority', models.CharField(choices=[('LOW', 'Low'), ('REG', 'Regular'), ('FST', 'Freshman'), ('GRD', 'Graduating'), ('CCO', 'Cadet Officer')], default='REG', max_length=3)),
                ('registration_priority', models.CharField(choices=[('LOW', 'Low'), ('REG', 'Regular'), ('FST', 'Freshman'), ('GRD', 'Graduating'), ('CCO', 'Cadet Officer')], default='REG', max_length=3)),
                ('academic_eligibility', models.BooleanField(default=True)),
                ('accountability_status', models.BooleanField(default=True)),
                ('scholarship', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='status',
            new_name='user_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='academic_eligibility',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='accountability_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preenlistment_priority',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_priority',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scholarship',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='student_number',
        ),
    ]
