# Generated by Django 3.1.1 on 2020-09-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200907_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_eligibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accountability_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deficiencies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preenlistment_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('REG', 'Regular'), ('FST', 'Freshman'), ('GRD', 'Graduating'), ('CCO', 'Cadet Officer')], default='GRD', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('REG', 'Regular'), ('FST', 'Freshman'), ('GRD', 'Graduating'), ('CCO', 'Cadet Officer')], default='GRD', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registration_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='scholarship',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
