# Generated by Django 3.1.1 on 2020-09-08 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200909_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationstatus',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_status', to=settings.AUTH_USER_MODEL),
        ),
    ]
