# Generated by Django 3.1.1 on 2020-09-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_delinquency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delinquency',
            options={'verbose_name_plural': 'Delinquencies'},
        ),
        migrations.AddField(
            model_name='delinquency',
            name='date_settled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delinquency',
            name='settled',
            field=models.BooleanField(default=False),
        ),
    ]
