# Generated by Django 3.1.1 on 2020-09-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200910_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'First Semester'), (2, 'Second Semester'), (3, 'Midyear')])),
                ('start_year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
