# Generated by Django 3.1.1 on 2020-09-09 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_academicyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnlistingUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='backend.enlistingunit')),
            ],
            options={
                'ordering': ['department__code', 'last_name', 'first_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_year', '-semester']},
        ),
        migrations.CreateModel(
            name='RegularClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.PositiveIntegerField(unique=True)),
                ('course_code', models.CharField(max_length=32)),
                ('number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('credits', models.FloatField()),
                ('schedule', models.CharField(max_length=32)),
                ('total_slots', models.PositiveSmallIntegerField()),
                ('restrictions', models.TextField()),
                ('instructor', models.ManyToManyField(related_name='classes', to='backend.Instructor')),
            ],
            options={
                'ordering': ['-class_code'],
            },
        ),
    ]
