# Generated by Django 3.1.1 on 2020-09-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200911_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='restrictions',
            field=models.TextField(blank=True),
        ),
    ]
