# Generated by Django 3.1.1 on 2020-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200911_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclass',
            name='enlisted',
            field=models.ManyToManyField(related_name='classes', to='backend.UserRegistrationStatus'),
        ),
    ]
