# Generated by Django 3.1.1 on 2020-09-10 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_regularclass_enlisted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='enlisted',
            field=models.ManyToManyField(related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
