# Generated by Django 3.1.1 on 2020-09-10 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200911_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='enlisted',
            field=models.ManyToManyField(blank=True, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
