# Generated by Django 3.1.1 on 2020-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200911_0154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularclass',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Regular classes'},
        ),
        migrations.RenameField(
            model_name='regularclass',
            old_name='course_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='regularclass',
            name='class_code',
        ),
        migrations.AlterField(
            model_name='regularclass',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
