# Generated by Django 3.1.1 on 2020-09-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20200911_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='father_status',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'Alive'), ('D', 'Deceased'), ('U', 'Unknown')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mother_status',
            field=models.CharField(blank=True, choices=[('', ''), ('A', 'Alive'), ('D', 'Deceased'), ('U', 'Unknown')], default='', max_length=1),
        ),
    ]
