# Generated by Django 3.1.1 on 2020-09-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200911_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistrationstatus',
            options={'ordering': ['-student_number'], 'verbose_name_plural': 'User registration status'},
        ),
    ]
