# Generated by Django 3.1.1 on 2020-09-11 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200911_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='enlisted',
            field=models.ManyToManyField(blank=True, related_name='enlisted_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='regularclass',
            name='instructor',
            field=models.ManyToManyField(blank=True, related_name='handled_classes', to='backend.Instructor'),
        ),
    ]
