# Generated by Django 3.1.1 on 2020-09-11 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_auto_20200911_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
