# Generated by Django 3.1.1 on 2020-09-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20200911_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.regularclass')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.academicyear')),
            ],
        ),
        migrations.AddField(
            model_name='userregistrationstatus',
            name='classes_taken',
            field=models.ManyToManyField(blank=True, related_name='enlisted_students', to='backend.ClassTaken'),
        ),
    ]
