# Generated by Django 3.1.1 on 2020-09-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20200911_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationstatus',
            name='first_enrolled',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='freshmen', to='backend.academicyear'),
        ),
    ]
