# Generated by Django 3.1.1 on 2020-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_userregistrationstatus_first_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationstatus',
            name='is_crs_admin',
            field=models.BooleanField(default=False),
        ),
    ]
