# Generated by Django 3.1.1 on 2020-09-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_userregistrationstatus_is_crs_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistrationstatus',
            name='user_status',
            field=models.CharField(blank=True, choices=[('STD', 'Student'), ('JFC', 'Junior Faculty'), ('SFC', 'Senior Faculty'), ('STF', 'Staff')], max_length=4, null=True),
        ),
    ]
