# Generated by Django 3.1.1 on 2020-09-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_classtaken_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtaken',
            options={'verbose_name_plural': 'Classes taken'},
        ),
        migrations.AddField(
            model_name='regularclass',
            name='section',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
