# Generated by Django 3.1.1 on 2020-09-12 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20200913_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classtaken',
            options={'ordering': ['cls__semester__start_year', 'cls__semester__semester'], 'verbose_name_plural': 'Classes taken'},
        ),
        migrations.RemoveField(
            model_name='classtaken',
            name='semester',
        ),
        migrations.AddField(
            model_name='regularclass',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='backend.academicyear'),
            preserve_default=False,
        ),
    ]
