# Generated by Django 3.1.1 on 2020-09-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_regularclass_exclude_gwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclass',
            name='enlisting_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='backend.enlistingunit'),
        ),
    ]
