# Generated by Django 3.1.1 on 2020-09-13 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_regularclass_enlisting_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclass',
            name='linked_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.regularclass'),
        ),
    ]
