# Generated by Django 3.1.1 on 2020-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_regularclass_linked_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='number',
            field=models.FloatField(),
        ),
    ]
