# Generated by Django 3.1.1 on 2020-09-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_auto_20200913_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclass',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
