# Generated by Django 3.1.1 on 2020-09-13 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_regularclass_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularclass',
            name='enlisting_unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='backend.enlistingunit'),
            preserve_default=False,
        ),
    ]
