# Generated by Django 3.1.1 on 2020-09-14 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20200914_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularclass',
            name='demand',
            field=models.ManyToManyField(blank=True, related_name='desired_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularclass',
            name='waitlist',
            field=models.ManyToManyField(blank=True, related_name='waitlisted_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
