# Generated by Django 3.1.1 on 2020-09-18 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_auto_20200914_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtaken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
