# Generated by Django 3.1.1 on 2020-09-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20200918_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtaken',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('D', 'Desired'), ('E', 'Enlisted'), ('W', 'Waitlisted'), ('X', 'Cancelled'), ('P', 'Passed'), ('F', 'Failed'), ('C', 'Conditional')], max_length=4),
        ),
    ]
