# Generated by Django 3.1.1 on 2020-09-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20200918_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
        migrations.AlterField(
            model_name='classtaken',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.regularclass', verbose_name='class_list'),
        ),
    ]
