# Generated by Django 3.1.1 on 2020-09-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_auto_20200919_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrsStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('P', 'Preenlistment'), ('W', 'Waitlisting'), ('D0', 'Dropping'), ('D1', 'Post-dropping'), ('C', 'Closed')], max_length=4)),
                ('set_available', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='classtaken',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_list', to='backend.regularclass', verbose_name='class'),
        ),
    ]
