# Generated by Django 3.1.1 on 2020-09-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20200919_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crsstatus',
            options={'verbose_name_plural': 'CRS Status'},
        ),
        migrations.AlterField(
            model_name='crsstatus',
            name='set_available',
            field=models.BooleanField(verbose_name='SET available'),
        ),
    ]
